# Generated by Django 4.1.4 on 2022-12-13 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpeedPayWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        max_digits=9,
                        verbose_name="wallet balance",
                    ),
                ),
                (
                    "wallet_uuid",
                    models.CharField(
                        db_index=True,
                        default="wallet_883a137bc9dd42aa95fde19897f261d3",
                        max_length=80,
                        verbose_name="user uuid",
                    ),
                ),
                (
                    "last_withdrawn",
                    models.DateTimeField(
                        null=True,
                        verbose_name="time of last withdrawal",
                    ),
                ),
                (
                    "last_deposited",
                    models.DateTimeField(
                        null=True,
                        verbose_name="time of last deposit",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "speedpay_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="speedpay user",
                    ),
                ),
            ],
        ),
    ]
