# Generated by Django 4.1.4 on 2022-12-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpaywallet",
            name="wallet_uuid",
            field=models.CharField(
                db_index=True,
                default="wallet_e8b4bcb1506d44d3b0fcf21da55d1885",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
