# Generated by Django 4.1.4 on 2022-12-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0003_alter_speedpaywallet_wallet_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpaywallet",
            name="wallet_uuid",
            field=models.CharField(
                db_index=True,
                default="wallet_7e12aa39ec4d49bc90829d46e453a86b",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
