# Generated by Django 4.1.4 on 2022-12-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="speedpayuser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="admin status"),
        ),
        migrations.AlterField(
            model_name="speedpayuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active status"),
        ),
        migrations.AlterField(
            model_name="speedpayuser",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default="user_f309e3b7a8434c59b0eac7580fb254a7",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
