# Generated by Django 4.1.4 on 2022-12-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpayuser",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default="user_d1c12d8ad1ad4ce4bb6c29e2525c1b9e",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
