# Generated by Django 4.1.4 on 2022-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_speedpayuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpayuser",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default="user_9b6594f1beaa4d6b8c8e9e10ee6201a3",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
