# Generated by Django 4.1.4 on 2022-12-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_speedpayuser_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="speedpayuser",
            name="uuid",
        ),
        migrations.AddField(
            model_name="speedpayuser",
            name="user_uuid",
            field=models.CharField(
                db_index=True,
                default="user_509290cce3ac4137aca1bd5c8b4f16b0",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
