# Generated by Django 4.1.4 on 2022-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speedpay_wallets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpaywallet",
            name="wallet_uuid",
            field=models.CharField(
                db_index=True,
                default="wallet_5206c7a15a034ed083de693631268868",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
