# Generated by Django 4.1.4 on 2022-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speedpay_wallets", "0002_alter_speedpaywallet_wallet_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpaywallet",
            name="balance",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=9,
                verbose_name="wallet balance",
            ),
        ),
        migrations.AlterField(
            model_name="speedpaywallet",
            name="wallet_uuid",
            field=models.CharField(
                db_index=True,
                default="wallet_baf2ae3cc6054295b42a6a3c975013ba",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
