# Generated by Django 4.1.4 on 2022-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speedpay_users", "0002_alter_speedpayuser_is_active_alter_speedpayuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpayuser",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
        migrations.AlterField(
            model_name="speedpayuser",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default="user_d690407afe3d4d3e92d117695301a112",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
