# Generated by Django 4.1.4 on 2022-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speedpay_users", "0003_alter_speedpayuser_email_alter_speedpayuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpayuser",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default="user_4e93a626d0a94eb3af93737a97ca7770",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
