# Generated by Django 4.1.4 on 2022-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("speedpay_users", "0004_alter_speedpayuser_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="speedpayuser",
            name="uuid",
            field=models.CharField(
                db_index=True,
                default="user_64b023825e6d4e70bed7d7a76367307b",
                max_length=80,
                verbose_name="user uuid",
            ),
        ),
    ]
